name: 'Promote ECR Image'
author: DevOps
description: 'Promote an ECR Image from one AWS account to another.'

inputs:
  source-aws-access-key-id:
    description: 'The source AWS Access key for authentication.'
    required: true
  source-aws-secret-access-key:
    description: 'The source AWS Secret key for authentication.'
    required: true
  source-aws-region:
    description: 'The source AWS Region for authentication.'
    required: false
    default: 'us-east-1'
  destination-aws-access-key-id:
    description: 'The destination AWS Access key for authentication.'
    required: true
  destination-aws-secret-access-key:
    description: 'The destination AWS Secret key for authentication.'
    required: true
  destination-aws-region:
    description: 'The source AWS Region for authentication.'
    required: false
    default: 'us-east-1'
  ecr-repo-name:
    description: 'The name of the ECR repository to use and create in the destination account. This is also the image name. The branch will be added automatically if necessary.'
    required: true
  image-tag:
    description: 'The image tag to pull.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate with Source AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.source-aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.source-aws-secret-access-key }}
        aws-region: ${{ inputs.source-aws-region }}

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
          export UNESCAPED_BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch=$(echo ${UNESCAPED_BRANCH_NAME})" >> $GITHUB_OUTPUT
          echo "clean-branch=$(echo ${UNESCAPED_BRANCH_NAME} | sed 's/_//g' | tr '[:upper:]' '[:lower:]' | cut -c -38)" >> $GITHUB_OUTPUT

    - name: Set ECR Repo Name
      id: ecr-repo-name-prep
      shell: bash
      run: |
        if [[ "${{ steps.extract_branch.outputs.branch }}" =~ (main|master) ]]; then
          echo "ecr-repo=${{ inputs.ecr-repo-name }}" >> $GITHUB_OUTPUT
        else
          echo "ecr-repo=$(echo ${{ inputs.ecr-repo-name }}/${{ steps.extract_branch.outputs.clean-branch }})" >> $GITHUB_OUTPUT
        fi

    - name: Login to Source AWS ECR
      id: login-source-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Pull ECR Image
      id: pull-ecr-image
      shell: bash
      run: docker pull ${{ steps.login-source-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:${{ github.sha }}

    - name: Authenticate with Destination AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.destination-aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.destination-aws-secret-access-key }}
        aws-region: ${{ inputs.destination-aws-region }}

    - name: Login to Destination AWS ECR
      id: login-destination-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Create ECR Repository
      shell: bash
      run: aws ecr create-repository --repository-name ${{ steps.ecr-repo-name-prep.outputs.ecr-repo }} --tags Key=repository,Value=${{ steps.ecr-repo-name-prep.outputs.ecr-repo }} || echo "Repository exists already. Skipping creation."

    - name: Tag ECR Image
      id: tag-ecr-image
      shell: bash
      run: |
        docker tag ${{ steps.login-source-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:${{ github.sha }} ${{ steps.login-destination-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:${{ github.sha }}
        docker tag ${{ steps.login-source-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:${{ github.sha }} ${{ steps.login-destination-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:latest

    - name: Push ECR Image
      id: push-ecr-image
      shell: bash
      run: |
        docker push ${{ steps.login-destination-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:latest
        docker push ${{ steps.login-destination-ecr.outputs.registry }}/${{ steps.ecr-repo-name-prep.outputs.ecr-repo }}:${{ github.sha }}